name = "cosmic-3d-prints"
account_id = "ad41fa20d2c4e8e8efbb86e2622b841"
main = "cloudflare-worker/src/index.js"
compatibility_date = "2026-09-20"

[vars]
FIREBASE_PROJECT_ID = "cosmic-3d-bc4d3"
IMAGEKIT_PUBLIC_KEY = "public_Fzs4VZA4lK9D9u5TOUW7p/889Ww="
ALLOWED_ORIGIN = "https://ashishpandey369.github.io"
